# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

font_family		Courier Prime
bold_font		Courier Prime Bold
italic_font		Courier Prime Italic
bold_italic_font	Courier Prime Bold Italic

cursor_shape	beam

enable_audio_bell no

window_padding_width	30

map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard

background 		#20282c
foreground 		#ebebeb
cursor 			#ebebeb

selection_foreground  	#20282c
selection_background  	#2a7893

# black
color0  		#20282c
color8  		#20282c

# red
color1  		#db7a6d
color9  		#db7a6d

# green
color2  		#b3d89c
color10 		#b3d89c

# yellow
color3  		#ffee88
color11 		#ffee88

# blue
color4  		#7ca5b8
color12 		#7ca5b8

# magenta
color5  		#b78f9c
color13 		#b78f9c

# cyan
color6  		#6da699
color14 		#6da699

# white
color7  		#ebebeb
color15 		#ebebeb
