# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

font_family		Courier Prime
bold_font		Courier Prime Bold	
italic_font		Courier Prime Italic
bold_italic_font	Courier Prime Bold Italic

cursor_shape	beam

enable_audio_bell no

window_padding_width	30

map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard

foreground		#e3dfdb
background		#1d2329
selection_foreground	#DCBDC0
selection_background	#1d2329

cursor			#e3dfdb
url_color		#75888A

# black
color0			#1d2329
color8			#9e9c99

# red
color1			#B97787
color9			#B97787

# green
color2  		#75888A
color10 		#75888A

# yellow
color3  		#A4A6A0
color11 		#A4A6A0

# blue
color4  		#D3A8AD
color12 		#D3A8AD

# magenta
color5  		#D0C8B7
color13 		#D0C8B7

# cyan
color6  		#DCBDC0
color14 		#DCBDC0

# white
color7  		#e3dfdb
color15 		#e3dfdb
