#!/bin/sh

total="$(free -h | grep Mem: | awk '{ print $2 }')"
used="$(free -h | grep Mem: | awk '{ print $3 }')"
free="$(free -h | grep Mem: | awk '{ print $4 }')"
percent="$(printf "%.0f\n" $(free -m | grep Mem | awk '{print ($3/$2)*100}'))"

if [ "$1" = "total" ]; then
    echo $total
elif [ "$1" = "used" ]; then
    echo $used
elif [ "$1" = "free" ]; then
    echo $free
elif [ "$1" = "percent" ]; then
    echo $percent
fi
