#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          32
bspc config top_padding         24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer   true

bspc rule -a firefox desktop='^1' follow=on
bspc rule -a lightcord desktop='^4'
bspc rule -a Spotify desktop='^5'
bspc rule -a Gimp desktop='^8'
bspc rule -a jetbrains-toolbox desktop='^2' state=floating
bspc rule -a jetbrains-pycharm desktop='^2'


# Autostart
pkill sxhkd 
sxhkd &

pkill polybar
~/.config/polybar/launch.sh

picom &

pkill dunst
dunst &

feh --bg-fill ~/wallpaper.*
