#!/bin/bash

black=$'\e[30m'
red=$'\e[31m'
green=$'\e[32m'
yellow=$'\e[33m'
blue=$'\e[34m'
magenta=$'\e[35m'
cyan=$'\e[36m'
gray=$'\e[37m'

reset=$'\e[0m'
bold=$'\e[1m'

echo -e "
 $bold
 $red████████ $green████████ $yellow████████ $blue████████ $magenta████████ $cyan████████ 
 $red████████ $green████████ $yellow████████ $blue████████ $magenta████████ $cyan████████ 
 $red████████ $green████████ $yellow████████ $blue████████ $magenta████████ $cyan████████ 
 $reset██████$gray██ $reset██████$gray██ $reset██████$gray██ $reset██████$gray██ $reset██████$gray██ $reset██████$gray██$reset 
 $red{color1}  $green{color2}  $yellow{color3}  $blue{color4}  $magenta{color5}  $cyan{color6}$reset
"
